---
name: oobabooga-text-generation-webui
version: 2024.04.28
slug: text-generation-webui
description: "A tool for running Large Language Models"
url: "https://github.com/oobabooga/text-generation-webui"
init: false
arch:
  - amd64
  - aarch64
ports:
  7860/tcp: 7860 # ingress
  5000/tcp: 5000 # api
ports_description:
  7860/tcp: Web interface (Not required for Ingress)
  5000/tcp: OpenAI compatible API Server
ingress: true
ingress_port: 7860
options: {}
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  models_directory: str?
map:
  - media:rw
  - share:rw
  - addon_config:rw